#!/bin/python
print("**********")
print("Main Menu")
print("1.Supported Refrigerants")
print("2.Search the characteristic of refrigerant")
print("3.Calculate m1, m2, m3 in Annex GG")
print("**********")
while 1:
    R32={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":648,
        "Lower_flammability_limit":0.307
        }
    R50={
        "Safety_group":"A3",
        "Auto_ignition_temperature":645,
        "Lower_flammability_limit":0.032
        }
    R143a={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":750,
        "Lower_flammability_limit":0.282
        }
    R152a={
        "Safety_group":"A2",
        "Auto_ignition_temperature":455,
        "Lower_flammability_limit":0.130
        }
    R170={
        "Safety_group":"A3",
        "Auto_ignition_temperature":515,
        "Lower_flammability_limit":0.038
        }
    R290={
        "Safety_group":"A3",
        "Auto_ignition_temperature":470,
        "Lower_flammability_limit":0.038
        }
    R600={
        "Safety_group":"A3",
        "Auto_ignition_temperature":365,
        "Lower_flammability_limit":0.038
        }
    R600a={
        "Safety_group":"A3",
        "Auto_ignition_temperature":460,
        "Lower_flammability_limit":0.043
        }
    R1150={
        "Safety_group":"A3",
        "Auto_ignition_temperature":425,
        "Lower_flammability_limit":0.036
        }
    R1270={
        "Safety_group":"A3",
        "Auto_ignition_temperature":455,
        "Lower_flammability_limit":0.046
        }
    E170={
        "Safety_group":"A3",
        "Auto_ignition_temperature":235,
        "Lower_flammability_limit":0.046
        }
    R142b={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":750,
        "Lower_flammability_limit":0.329
        }
    R1234yf={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":405,
        "Lower_flammability_limit":0.289
        }
    R1234ze={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":368,
        "Lower_flammability_limit":0.303
        }
    R444A={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":"ND",
        "Lower_flammability_limit":0.324
        }
    R444B={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":"ND",
        "Lower_flammability_limit":0.277
        }
    R447A={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":"ND",
        "Lower_flammability_limit":0.304
        }
    R447B={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":"ND",
        "Lower_flammability_limit":0.312
        }
    R451A={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":"ND",
        "Lower_flammability_limit":0.322
        }
    R451B={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":"ND",
        "Lower_flammability_limit":0.322
        }
    R452B={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":"ND",
        "Lower_flammability_limit":0.309
        }
    R454A={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":"ND",
        "Lower_flammability_limit":0.273
        }
    R454B={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":"ND",
        "Lower_flammability_limit":0.307
        }
    R454C={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":"ND",
        "Lower_flammability_limit":0.286
        }
    R457A={
        "Safety_group":"A2L",
        "Auto_ignition_temperature":"ND",
        "Lower_flammability_limit":0.215
        }
    R=input("Please input the refrigerant designation:")
    index=["Safety_group","Auto_ignition_temperature","Lower_flammability_limit"]
    for i in index:
        print(i+":"+str(R[i]))

    tmp=input("Press 'e' to exit! Others to contine!")
    if tmp=="e":
        break
    else:
        continue
